target 'Example' do
  platform :ios, '10.2'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'freewheel', path: '../'
  pod 'MyLibrary', path: './MyLibrary'

end

target 'Example-tvOS' do
  platform :tvos, '12.2'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'freewheel', path: '../'
  pod 'MyLibrary', path: './MyLibrary'

end
